### ISSUE TITLE
The programme use ram as ramdisk in AMD GPUs

### ISSUE THREAD

**Issue by VFXNO** [abesada/GpuRamDrive#2]
the programme doesnt work ,it use the ram system instead of vram. one of your member fixed it  in 0.5 Version but still has issues I cant add more than 1024MB   I hope you fix it because alot of people has Amd Gpu with huge vram .

**Comment by abesada** [comment]
Hi @bisher13, I've created two versions:

* Bzrr: requires as much RAM memory as the size of the unit, after initialisation it is released.
* Vendor: similar to the Bzrr version but does not require the use of RAM. Detects the type of card to initialise AMDs with other flags

Both versions are slower than the current version, around 60% performance.

[GpuRamDrive_v012.zip](https://github.com/abesada/GpuRamDrive/files/5781291/GpuRamDrive_v012.zip)

I'm waiting for your feedback

**Comment by Telluryon** [comment]
Hi,

i have just testet the two versions: Vendor works great, it lets me use the full ram of my card (RX480 8G). But Bzrr seems to allocate twice the amout of system ram than stated upon initialising. Giving me an "unable to create memory buffer" when i try to set up large drives. So i can only use around 5G for the drive while having 16G of memory.

**Comment by abesada** [comment]
@Telluryon, a lot of thanks for your feedback, update to 0.12 version with vendor implementation.
